import { App, SuggestModal } from 'obsidian';
import { t } from '../../../i18n';
import { transcriptLanguageDisplayName } from '../../../constants/languages';
import type { AvailableTranscriptTrack } from '../../../types/transcript-languages';

/** Row text for a caption track: YouTube's own label, else the English name (+ auto-generated). */
export function captionTrackLabel(track: AvailableTranscriptTrack): string {
  if (track.name) return track.name;
  const name = transcriptLanguageDisplayName(track.language);
  return track.kind === 'asr' ? `${name} · ${t('tlang.autoGenerated')}` : name;
}

/**
 * Picker for the video's live caption tracks (`GET …/transcripts/available`).
 * Default/added rows stay visible so the list matches the video; the caller
 * decides what choosing them means.
 */
export class CaptionLanguageSuggestModal extends SuggestModal<AvailableTranscriptTrack> {
  constructor(
    app: App,
    private readonly tracks: AvailableTranscriptTrack[],
    private readonly onChoose: (track: AvailableTranscriptTrack) => void
  ) {
    super(app);
    this.setPlaceholder(t('tlang.menuTitle'));
    this.emptyStateText = t('tlang.noneAvailable');
  }

  getSuggestions(query: string): AvailableTranscriptTrack[] {
    const q = query.trim().toLowerCase();
    if (!q) return this.tracks;
    return this.tracks.filter((track) =>
      `${captionTrackLabel(track)} ${transcriptLanguageDisplayName(track.language)} ${track.language}`
        .toLowerCase()
        .includes(q));
  }

  renderSuggestion(track: AvailableTranscriptTrack, el: HTMLElement): void {
    el.createDiv({ text: captionTrackLabel(track) });
    const state = track.state === 'primary' ? t('tlang.stateDefault') : track.state === 'added' ? t('tlang.stateAdded') : '';
    if (state) el.createEl('small', { text: state, cls: 'sa-text-muted' });
  }

  onChooseSuggestion(track: AvailableTranscriptTrack): void {
    this.onChoose(track);
  }
}
