/**
 * YouTube caption languages — transcript "+" control, tab menu, sync notices
 * (prd-youtube-transcript-languages §5.1, plan §11). Key prefix "tlang.".
 */
import type { LocaleText } from '../index';

export const transcriptLanguageStrings = {
  'tlang.menuTitle': { en: 'Transcript languages', ko: '자막 언어' },
  'tlang.addLanguage': { en: 'Add language…', ko: '언어 추가…' },
  'tlang.addCaptions': { en: 'Add captions…', ko: '자막 추가…' },
  'tlang.transcribeWhisper': { en: 'Transcribe with Whisper', ko: 'Whisper로 전사' },
  'tlang.loading': { en: 'Loading languages…', ko: '언어 목록을 불러오는 중…' },
  'tlang.noneAvailable': { en: 'No other caption languages for this video', ko: '이 영상에는 다른 자막 언어가 없습니다' },
  'tlang.noCaptions': { en: 'This video has no captions on YouTube.', ko: '이 영상에는 YouTube 자막이 없습니다.' },
  'tlang.setDefault': { en: 'Set as default', ko: '기본으로 설정' },
  'tlang.delete': { en: 'Delete language', ko: '언어 삭제' },
  'tlang.added': { en: '{language} captions added', ko: '{language} 자막을 추가했습니다' },
  'tlang.removed': { en: '{language} captions removed', ko: '{language} 자막을 삭제했습니다' },
  'tlang.defaultSet': { en: '{language} is now the default', ko: '이제 {language} 자막이 기본입니다' },
  'tlang.stateDefault': { en: 'Default', ko: '기본' },
  'tlang.stateAdded': { en: 'Added', ko: '추가됨' },
  'tlang.autoGenerated': { en: 'auto-generated', ko: '자동 생성' },
  'tlang.unknownLanguage': { en: 'Unknown language', ko: '알 수 없는 언어' },
  'tlang.alreadyDefault': { en: '{language} is already the default', ko: '{language} 자막이 이미 기본입니다' },
  'tlang.aiConflict': {
    en: 'A translated {language} transcript already exists in this note; captions were not added',
    ko: '이 노트에 번역된 {language} 자막이 이미 있어 자막을 추가하지 않았습니다',
  },
  'tlang.localOnly': {
    en: 'Upload this note to your account to manage caption languages.',
    ko: '자막 언어를 관리하려면 이 노트를 계정에 업로드하세요.',
  },
  'tlang.signIn': { en: 'Sign in to manage caption languages.', ko: '자막 언어를 관리하려면 로그인하세요.' },
  'tlang.error.unavailable': {
    en: 'This video has no {language} captions. Try AI translation instead.',
    ko: '이 영상에는 {language} 자막이 없습니다. AI 번역을 이용해 보세요.',
  },
  'tlang.error.limit': { en: 'You can add up to 10 caption languages.', ko: '자막 언어는 최대 10개까지 추가할 수 있습니다.' },
  'tlang.error.primaryNotDeletable': {
    en: 'Set another language as default first.',
    ko: '먼저 다른 언어를 기본으로 설정하세요.',
  },
  'tlang.error.isPrimary': { en: '{language} is already the default.', ko: '{language} 자막이 이미 기본입니다.' },
  'tlang.error.tooLarge': {
    en: 'These captions are too long to set as default.',
    ko: '자막이 너무 길어 기본으로 설정할 수 없습니다.',
  },
  'tlang.error.tooLargeToAdd': {
    en: '{language} captions are too long to save to this archive.',
    ko: '{language} 자막이 너무 길어 이 아카이브에 저장할 수 없습니다.',
  },
  'tlang.error.rateLimited': {
    en: 'Too many caption requests. Try again in a few minutes.',
    ko: '자막 요청이 너무 많습니다. 몇 분 후 다시 시도하세요.',
  },
  'tlang.error.videoUnavailable': {
    en: "Captions aren't available for this video.",
    ko: '이 영상의 자막을 가져올 수 없습니다.',
  },
  'tlang.error.generic': { en: "Couldn't update captions. Try again.", ko: '자막을 업데이트하지 못했습니다. 다시 시도하세요.' },
} satisfies Record<string, LocaleText>;
